### ISSUE TITLE
uniswapv3 total value locked and tick data corrections

### ISSUE THREAD

**Issue by Seth-Schmidt** [PowerLoom/snapshotter-computes#1]
## Describe the bug 
The current uniswapv3 implementation does not compute the correct "total value locked" for liquidity pools in ./total_value_locked.py's caclulate_reserves() function. Additionally, calls to the UniswapV3 helper contract's getTicks() function are very expensive, and they will currently be unnecessarily duplicated if called in multiple processes.

## To Reproduce
**Affected versions**: uniswapv3 branch

To reproduce, run the pooler/tests/test_tvl.py test. This will fail due to inaccurate computed reserves.

**Expected behavior**
test_tvl.py should pass, indicating that the tvl calculation is within accepted accuracy.
get_tick_data() in ./total_value_locked.py should successfully store ticks on the first call, and retrieve cached tick data on a duplicate call.

**Proposed Solution**
The current calculate_reserves() function retrieves and calculates duplicate ticks. I will change it to get each tick only once.
Calculate_reserves() also does not properly combine batched tick retrieval calls, leaving half of the retrieved ticks unprocessed. I will fix the tick processing to include every initialized tick in the pool. Additionally, storing tick data using the given redis connection will be added.

**Caveats**
None

**Additional context**
issues brought to my attention by @getjiggy

**Comment by getjiggy** [comment]
closing issue. merged pr.
